const $=s=>document.querySelector(s); const app=$('#app');
const defaults={matricule:'',statut:'CANDIDAT',accreditation:'0',affectation:'—',inventaire:null,progression:0,messages:1,installed:false,tendances:{PERCEPTION:0,ADAPTATION:0,CONSEQUENCE:0,CONTINUITE:0,TEMPORISATION:0}};
let S={...defaults,...JSON.parse(localStorage.getItem('ordre_terminal')||'{}')};
function save(){localStorage.setItem('ordre_terminal',JSON.stringify(S))} function shell(body,status='SYS // SESSION : 1'){app.innerHTML=`<section class="shell"><div class="brand">ORDRE DES CINQ OMBRES</div><div class="rule"></div>${body}<div class="status">PROTOCOLE ACTIF : 000 <span class="tag">${status}</span></div></section>`}
function later(fn,ms=650){setTimeout(fn,ms)}
function boot(){shell(`<div class="terminal cursor">RÉSEAU DES CINQ OMBRES\n\nINITIALISATION DU TERMINAL...\nCANAL SÉCURISÉ : ÉTABLI\n\nPROTOCOLE ACTIF : 000\nIDENTIFICATION REQUISE\n\n&gt; </div>`,'CONNEXION');later(()=>S.matricule?environment():identify(),1500)}
function identify(){shell(`<h1 class="title">PROTOCOLE 000</h1><p class="sub">RECRUTEMENT // IDENTIFICATION REQUISE</p><div class="rule"></div><label class="tiny">IDENTIFIANT CANDIDAT</label><input id="id" class="input" maxlength="20" placeholder="C-021-7F3" autocomplete="off"><div class="menu"><button class="btn primary" id="ok">[ VALIDER ]</button></div><div id="err" class="system"></div>`);$('#ok').onclick=()=>{let v=$('#id').value.trim().toUpperCase();if(v.length<5){$('#err').textContent='SYS // IDENTIFIANT NON RECONNU';return}S.matricule=v;save();shell(`<div class="terminal">IDENTIFIANT RECONNU.\n\nOUVERTURE D'UNE SESSION TEMPORAIRE...</div>`,'AUTHENTIFICATION');later(environment,900)}}
function standalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function environment(){if(standalone()){S.installed=true;save();shell(`<div class="terminal">POINT D'ACCÈS DÉTECTÉ.\n\nAPPAREIL ENREGISTRÉ.\nCANAL CANDIDAT ÉTABLI.\n\nPROTOCOLE 000 AUTORISÉ.</div>`,'POINT D’ACCÈS ACTIF');later(home,1100)}else{shell(`<h1 class="title">ENVIRONNEMENT NON PERSISTANT</h1><p class="sub">Installation d'un point d'accès local recommandée. Cette opération permet les connexions ultérieures depuis votre appareil.</p><div class="menu"><button class="btn primary" id="install">[ ÉTABLIR LE POINT D'ACCÈS ]</button><button class="btn" id="continue">[ POURSUIVRE CETTE SESSION ]</button></div>`);$('#install').onclick=installHelp;$('#continue').onclick=home}}
function installHelp(){shell(`<h1 class="title">AUTORISATION SYSTÈME REQUISE</h1><div class="terminal">LE TERMINAL NE DISPOSE PAS DES PRIVILÈGES NÉCESSAIRES POUR MODIFIER VOTRE APPAREIL.\n\nOUVREZ LES OPTIONS DE PARTAGE DE VOTRE NAVIGATEUR.\n\nSÉLECTIONNEZ :\n« SUR L'ÉCRAN D'ACCUEIL »\n\nCONSERVEZ LE NOM : TERMINAL\n\nPUIS OUVREZ LE POINT D'ACCÈS NOUVELLEMENT CRÉÉ.</div><div class="menu"><button class="btn" id="continue">[ POURSUIVRE CETTE SESSION ]</button></div>`,'AUTORISATION EXTERNE');$('#continue').onclick=home}
function home(){shell(`<h1 class="title">TERMINAL // ACCÈS CANDIDAT</h1><div class="kv"><b>CANDIDAT</b><span>${S.matricule}</span><b>STATUT</b><span>EN ÉVALUATION</span><b>ACCRÉDITATION</b><span>0</span><b>AFFECTATION</b><span>—</span></div><div class="rule"></div><div class="menu"><button class="btn" data-go="dossier">&gt; DOSSIER 000</button><button class="btn" data-go="evals">&gt; ÉVALUATIONS</button><button class="btn" data-go="messages">&gt; MESSAGERIE <span class="tag">[${S.messages}]</span></button><button class="btn" data-go="archives">&gt; ARCHIVES <span class="tag">[×]</span></button><button class="btn" data-go="profile">&gt; PROFIL</button></div><div class="system">SYS // ÉTAT : EN ATTENTE</div>`);document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>views[b.dataset.go]())}
const back=()=>`<button class="btn back" id="back">[ RETOUR ]</button>`;function wireBack(){let b=$('#back');if(b)b.onclick=home}
function dossier(){if(S.inventaire===null){shell(`<h1 class="title">DOSSIER 000</h1><div class="kv"><b>DÉSIGNATION</b><span>RECRUTEMENT</span><b>STATUT</b><span>ACTIF</span><b>OBJECTIF</b><span>ÉVALUATION DU CANDIDAT</span><b>MODULES</b><span>5</span></div><div class="rule"></div><p class="sub">INSTRUCTION ACTIVE</p><div class="terminal">PROCÉDER À L'INVENTAIRE DU MATÉRIEL REÇU.</div><div class="menu"><button class="btn primary" id="start">[ COMMENCER ]</button></div>${back()}`);$('#start').onclick=inventory;wireBack()}else{shell(`<h1 class="title">DOSSIER 000</h1><div class="terminal">INVENTAIRE : ENREGISTRÉ\nÉVALUATIONS : ${S.progression} / 5\n\nINSTRUCTION ACTIVE : ${S.progression? 'POURSUIVRE LE PROTOCOLE.' : 'PROCÉDER AU MODULE I.'}</div>${back()}`);wireBack()}}
function inventory(){shell(`<h1 class="title">CONTRÔLE DU MATÉRIEL</h1><div class="terminal">ÉLÉMENTS ATTENDUS : 09\n\nRetirez tous les éléments du colis avant de poursuivre.\n\nVotre inventaire est-il conforme ?</div><div class="menu"><button class="btn ans">[ CONFORME ]</button><button class="btn ans">[ NON CONFORME ]</button><button class="btn ans">[ INCERTAIN ]</button></div>`);document.querySelectorAll('.ans').forEach(b=>b.onclick=()=>{S.inventaire=b.textContent.replace(/[\[\]]/g,'').trim();save();shell(`<div class="terminal">RÉPONSE ENREGISTRÉE.\n\nPROCÉDEZ AU MODULE I.</div>`,'INVENTAIRE CONSIGNÉ');later(home,1100)})}
function evals(){let rows=[1,2,3,4,5].map(n=>{let st=n<=S.progression?'ENREGISTRÉ':n===S.progression+1&&S.inventaire?'DISPONIBLE':'VERROUILLÉ';return `<div class="eval"><span>◇ &nbsp; ${['I','II','III','IV','V'][n-1]}</span><span>${st}</span></div>`}).join('');shell(`<h1 class="title">ÉVALUATIONS</h1>${rows}<p class="sub">PROGRESSION : ${S.progression} / 5</p>${back()}`);wireBack()}
function messages(){S.messages=0;save();shell(`<h1 class="title">MESSAGERIE</h1><div class="msg"><b>SUPERVISION — 000</b><p>Le matériel déclaré a été enregistré.</p><p>Procédez au Module I.</p><span class="tiny">AUCUNE RÉPONSE REQUISE.</span></div>${back()}`);wireBack()}
function archives(){shell(`<h1 class="title">ARCHIVES CENTRALES</h1><div class="terminal">VÉRIFICATION DES DROITS...\n\nSTATUT : CANDIDAT\nACCRÉDITATION : 0\n\nACCÈS REFUSÉ.\n\nLA TENTATIVE D'ACCÈS A ÉTÉ CONSIGNÉE.</div>${back()}`,'ACCÈS REFUSÉ');wireBack()}
function profile(){shell(`<h1 class="title">PROFIL</h1><div class="kv"><b>IDENTIFIANT</b><span>${S.matricule}</span><b>STATUT</b><span>CANDIDAT</span><b>ACCRÉDITATION</b><span>0</span><b>DIVISION</b><span>—</span><b>DOSSIERS TERMINÉS</b><span>0</span></div><div class="rule"></div><div class="terminal">AFFECTATION EN ATTENTE</div>${back()}`);wireBack()}
const views={dossier,evals,messages,archives,profile};
if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').catch(()=>{});boot();
